MyWeb_3/MyWeb_3/Models/Chude.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyWeb_3.Models
{
    public class Chude
    {
        public int ID { set; get; }
        public String Nguoitao { set; get; }
        [Required(ErrorMessage = ("Không bỏ trống!"))]
        [StringLength(50, ErrorMessage = "So luong ki tu trong khoang 5-->50", MinimumLength = 5)]
        public String Tieude { set; get; }
        [Required(ErrorMessage = ("Không bỏ trống!"))]
        [StringLength(5000, ErrorMessage = "So luong ki tu trong khoang 10-->5000", MinimumLength = 10)]
        public String Noidung { set; get; }
        [Required(ErrorMessage = ("Chưa nhập ngày"))]
        [DataType(DataType.Date)]
        public DateTime Ngaytao { set; get; }
        [Required(ErrorMessage = ("Chưa nhập ngày"))]
        [DataType(DataType.Date)]
        public DateTime Ngaychinhsua { set; get; }
        public int Luotcamon { set; get; }
        public int UserProfileUserId { set; get; }

        public virtual UserProfile UserProfile { set; get; }
        public virtual ICollection<Binhluan> Binhluans { set; get; }
    }
}

MyWeb_3/MyWeb_3/Controllers/BinhluanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyWeb_3.Models;

namespace MyWeb_3.Controllers
{
    [Authorize]
    public class BinhluanController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Binhluan/

        public ActionResult Index()
        {
            var binhluans = db.Binhluans.Include(b => b.Chude);
            return View(binhluans.ToList());
        }

        //
        // GET: /Binhluan/Details/5

        public ActionResult Details(int id = 0)
        {
            Binhluan binhluan = db.Binhluans.Find(id);
            if (binhluan == null)
            {
                return HttpNotFound();
            }
            return View(binhluan);
        }

        //
        // GET: /Binhluan/Create

        public ActionResult Create()
        {
            ViewBag.ChudeID = new SelectList(db.Chudes, "ID", "Nguoitao");
            return View();
        }

        //
        // POST: /Binhluan/Create

        [HttpPost]
        public ActionResult Create(Binhluan binhluan, int idpost)
        {
            if (ModelState.IsValid)
            {
                
                binhluan.ChudeID = idpost;
                binhluan.Ngaytao = DateTime.Now;
                binhluan.Ngaychinhsua = DateTime.Now;
                db.Binhluans.Add(binhluan);
                db.SaveChanges();
                return RedirectToAction("Details/" + idpost, "Chude");
            }

            ViewBag.ChudeID = new SelectList(db.Chudes, "ID", "Nguoitao", binhluan.ChudeID);
            return View(binhluan);
        }

        //
        // GET: /Binhluan/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Binhluan binhluan = db.Binhluans.Find(id);
            if (binhluan == null)
            {
                return HttpNotFound();
            }
            ViewBag.ChudeID = new SelectList(db.Chudes, "ID", "Nguoitao", binhluan.ChudeID);
            return View(binhluan);
        }

        //
        // POST: /Binhluan/Edit/5

        [HttpPost]
        public ActionResult Edit(Binhluan binhluan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(binhluan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ChudeID = new SelectList(db.Chudes, "ID", "Nguoitao", binhluan.ChudeID);
            return View(binhluan);
        }

        //
        // GET: /Binhluan/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Binhluan binhluan = db.Binhluans.Find(id);
            if (binhluan == null)
            {
                return HttpNotFound();
            }
            return View(binhluan);
        }

        //
        // POST: /Binhluan/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Binhluan binhluan = db.Binhluans.Find(id);
            db.Binhluans.Remove(binhluan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyWeb_3/MyWeb_3/Controllers/ChudeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyWeb_3.Models;

namespace MyWeb_3.Controllers
{
    [Authorize]
    public class ChudeController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Chude/

        public ActionResult Index()
        {
            var chudes = db.Chudes.Include(c => c.UserProfile);
            return View(chudes.ToList());
        }

        //
        // GET: /Chude/Details/5

        public ActionResult Details(int id = 0)
        {
            Chude chude = db.Chudes.Find(id);
            ViewData["idpost"] = id;
            if (chude == null)
            {
                return HttpNotFound();
            }
            return View(chude);
        }

        //
        // GET: /Chude/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Chude/Create

        [HttpPost]
        public ActionResult Create(Chude chude)
        {
            if (ModelState.IsValid)
            {
                chude.Ngaytao = DateTime.Now;
                chude.Ngaychinhsua = DateTime.Now;
                db.Chudes.Add(chude);
                db.SaveChanges();
                return RedirectToAction("Details/" + chude.ID, "Chude");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", chude.UserProfileUserId);
            return View(chude);
        }

        //
        // GET: /Chude/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Chude chude = db.Chudes.Find(id);
            if (chude == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", chude.UserProfileUserId);
            return View(chude);
        }

        //
        // POST: /Chude/Edit/5

        [HttpPost]
        public ActionResult Edit(Chude chude)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chude).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", chude.UserProfileUserId);
            return View(chude);
        }

        //
        // GET: /Chude/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Chude chude = db.Chudes.Find(id);
            if (chude == null)
            {
                return HttpNotFound();
            }
            return View(chude);
        }

        //
        // POST: /Chude/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Chude chude = db.Chudes.Find(id);
            db.Chudes.Remove(chude);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyWeb_3/MyWeb_3/Views/Chude/Create.cshtml
@model MyWeb_3.Models.Chude

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Chude</legend>

        <h5>Tiêu đề:</h5>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tieude)
            @Html.ValidationMessageFor(model => model.Tieude)
        </div>

        <h5>Nội dung:</h5>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Noidung)
            @Html.ValidationMessageFor(model => model.Noidung)
        </div>

        <h5> Người tạo:</h5>
        <div class="editor-field">
            @Html.DropDownList("UserProfileUserId", String.Empty)
            @Html.ValidationMessageFor(model => model.UserProfileUserId)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyWeb_3/MyWeb_3/Views/Chude/Delete.cshtml
@model MyWeb_3.Models.Chude

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Chude</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nguoitao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nguoitao)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Tieude)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Tieude)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Noidung)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Noidung)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Ngaytao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Ngaytao)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Ngaychinhsua)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Ngaychinhsua)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Luotcamon)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Luotcamon)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MyWeb_3/MyWeb_3/Views/Chude/Details.cshtml
@model MyWeb_3.Models.Chude

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Chude</legend>

    

    <h4>Tiêu đề</h4>
    <div class="display-field">
        @Html.DisplayFor(model => model.Tieude)
    </div>

    <h4>Nội dung</h4>
    <div class="display-field">
        @Html.DisplayFor(model => model.Noidung)
    </div>

    <h4>Ngày tạo</h4>
    <div class="display-field">
        @Html.DisplayFor(model => model.Ngaytao)
    </div>

    

    <h4>Lượt cảm ơn</h4>
    <div class="display-field">
        @Html.DisplayFor(model => model.Luotcamon)
    </div>

    <h4>Người tạo</h4>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>
<hr>
@Html.Partial("Them_Binhluan", new  MyWeb_3.Models.Binhluan(), ViewData);

<fieldset>
    <legend>Bình luận</legend>
    <div id ="result">
    <h3>Danh sách các bình luận:</h3>
    @foreach (var comment in Model.Binhluans.OrderByDescending(x=>x.Ngaytao).Take(10))
    {
        <div class="display-field">
        <h3> @Html.DisplayFor(x => comment.NDBinhluan)</h3>
        </div>
        <div class="display-field">
        <h4>Cách đây: @Html.DisplayFor(x => comment.LastTime) phút</h4>
        </div>
        <hr>
    }
    </div>
</fieldset>

<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyWeb_3/MyWeb_3/Views/Chude/Edit.cshtml
@model MyWeb_3.Models.Chude

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Chude</legend>

        @Html.HiddenFor(model => model.ID)

        

        <h5>Tiêu đề:</h5>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tieude)
            @Html.ValidationMessageFor(model => model.Tieude)
        </div>

        <h5>Nội dung:</h5>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Noidung)
            @Html.ValidationMessageFor(model => model.Noidung)
        </div>

        <h5> Người tạo:</h5>
        <div class="editor-field">
            @Html.DropDownList("UserProfileUserId", String.Empty)
            @Html.ValidationMessageFor(model => model.UserProfileUserId)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
    
    
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyWeb_3/MyWeb_3/Views/Chude/Index.cshtml
@model IEnumerable<MyWeb_3.Models.Chude>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            Tiêu đề
        </th>
        <th>
            Nội dung
        </th>
        <th>
            Ngày tạo
        </th>
        <th>
            Lượt cảm ơn
        </th>
        &nbsp; &nbsp;
        <th>
            Đăng bởi
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.Tieude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Noidung)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ngaytao)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.Luotcamon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserProfile.UserName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

MyWeb_3/MyWeb_3/Views/Chude/Them_Binhluan.cshtml
@model MyWeb_3.Models.Binhluan

@using (Html.BeginForm("Create", "Binhluan", new { idpost = ViewData["idpost"] }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Thêm bình luận</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.NDBinhluan)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NDBinhluan)
            @Html.ValidationMessageFor(model => model.NDBinhluan)
        </div>

        

        

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
    
}