Blog8/Blog8/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Blog8.Models
{
    [Table("Post")]
    public class Post
    {
        public int ID { set; get; }
        [Required(ErrorMessage = ("Khong bo trong"))]
        [StringLength(500, ErrorMessage = "So luong ki tu trong khoang 20-->500", MinimumLength = 20)]
        public String Title { set; get; }
        [Required(ErrorMessage = ("Khong bo trong"))]
        [StringLength(5000, ErrorMessage = "So luong ki tu toi thieu 50", MinimumLength = 50)]
        public String Body { set; get; }
        [Required(ErrorMessage = ("Chua nhap ngay"))]
        [DataType(DataType.Date)]
        public DateTime DateCreated { set; get; }
        [Required(ErrorMessage = ("Chua nhap ngay"))]
        [DataType(DataType.Date)]
        public DateTime DateUpdated { set; get; }
        [Required(ErrorMessage = ("Khong bo trong"))]
        public int UserProfileUserId { set; get; }

        public virtual UserProfile UserProfile { set; get; }
        public virtual ICollection<Comment> Comments { set; get; }
        public virtual ICollection<Tag> Tags { set; get; }
    }
}

Blog8/Blog8/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog8.Models;

namespace Blog8.Controllers
{
    public class CommentController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Comment/

        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Post);
            return View(comments.ToList());
        }

        //
        // GET: /Comment/Details/5

        public ActionResult Details(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // GET: /Comment/Create

        public ActionResult Create()
        {
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title");
            return View();
        }

        //
        // POST: /Comment/Create

        [HttpPost]
        public ActionResult Create(Comment comment,int idpost)
        {
            if (ModelState.IsValid)
            {
                comment.PostID = idpost;
                comment.DateCreated = DateTime.Now;
                comment.DateUpdated = DateTime.Now;
                db.Comments.Add(comment);
                db.SaveChanges();
                return PartialView("viewComment", comment);
                //return RedirectToAction("Details/"+idpost,"Post");
            }

            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        //
        // GET: /Comment/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        //
        // POST: /Comment/Edit/5

        [HttpPost]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        //
        // GET: /Comment/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Blog8/Blog8/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog8.Models;

namespace Blog8.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Post/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.UserProfile);
            return View(posts.ToList());
        }

        //
        // GET: /Post/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Find(id);
            ViewData["idpost"] = id;
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        public ActionResult Create(Post post,string Content)
        {
            if (ModelState.IsValid)
            {
                post.DateCreated = DateTime.Now;
                post.DateUpdated = DateTime.Now;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName }).
                    Where(y => y.UserName == User.Identity.Name).Single().UserId;

                post.UserProfileUserId = userid;

                //Tạo list các Tag
                List<Tag> Tags = new List<Tag>();
                //Tách các tag theo dấu ,
                string[] TagContent = Content.Split(',');
                //lặp các tag vừa tách
                foreach (string item in TagContent)
                {
                    //Tìm xem các tag content đã có hay chưa
                    Tag tagExits = null;
                    var ListTag = db.Tags.Where(y => y.Content.Equals(item));
                    if (ListTag.Count() > 0)
                    {
                        //nếu có tag rồi thì add thêm post vào
                        tagExits = ListTag.First();
                        tagExits.Posts.Add(post);
                    }
                    else
                    {
                        //nếu chưa có tag thì tạo mới
                        tagExits = new Tag();
                        tagExits.Content = item;
                        tagExits.Posts = new List<Post>();
                        tagExits.Posts.Add(post);
                    }
                    //add vào list các Tag
                    Tags.Add(tagExits);
                }
                //gán list tag cho post
                post.Tags = Tags;

                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Blog8/Blog8/Views/Post/Create.cshtml
@model Blog8.Models.Post

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <div class="editor-label">
            Tag:
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => new Blog8.Models.Tag().Content)
            @Html.ValidationMessageFor(model => new Blog8.Models.Tag().Content)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog8/Blog8/Views/Post/Delete.cshtml
@model Blog8.Models.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Post</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateCreated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreated)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateUpdated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateUpdated)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Blog8/Blog8/Views/Post/Details.cshtml
@model Blog8.Models.Post

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Post</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateCreated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreated)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateUpdated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateUpdated)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>

@Html.Partial("_addComment", new Blog8.Models.Comment(), ViewData);

<fieldset>
    <legend>Comment</legend>
    <div id ="result">
    <h3>Danh sách các bình luận:</h3>
    @foreach (var comment in Model.Comments.OrderByDescending(x=>x.DateCreated).Take(10))
    {
        <div class="display-field">
        <h3> @Html.DisplayFor(x => comment.Body)</h3>
        </div>
        <div class="display-field">
        <h4>Tác giả: @Html.DisplayFor(x => comment.Author)</h4>
        </div>
        <div class="display-field">
        <h4>Cách đây: @Html.DisplayFor(x => comment.LastTime) phút</h4>
        </div>
        <hr>
    }
    </div>
</fieldset>

<fieldset>
    <legend>Tag</legend>
    <h3>Danh sách các Tag:</h3>
    @foreach (var tag in Model.Tags)
    {
        <div class="display-field">
        <h4>@Html.ActionLink(tag.Content,"../Tag/Details",new { id = tag.TagID })</h4>
        </div>
        <hr>
    }
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Blog8/Blog8/Views/Post/Edit.cshtml
@model Blog8.Models.Post

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateCreated)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateCreated)
            @Html.ValidationMessageFor(model => model.DateCreated)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateUpdated)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateUpdated)
            @Html.ValidationMessageFor(model => model.DateUpdated)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserProfileUserId, "UserProfile")
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserProfileUserId", String.Empty)
            @Html.ValidationMessageFor(model => model.UserProfileUserId)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog8/Blog8/Views/Post/Index.cshtml
@model IEnumerable<Blog8.Models.Post>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateUpdated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserProfile.UserName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Body)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateUpdated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserProfile.UserName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

Blog8/Blog8/Views/Post/_addComment.cshtml
@model Blog8.Models.Comment

@using (Html.BeginForm("Create", "Comment",FormMethod.Post,new{id ="my-form"}))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Add Comment</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        

        <div class="editor-label">
            @Html.LabelFor(model => model.Author)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Author)
            @Html.ValidationMessageFor(model => model.Author)
        </div>
                                                @Html.Hidden("idpost",ViewData["idpost"])
        

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
    
}
<script src="~/Scripts/addComments.js"></script>